{{- if .Values.truefoundryApi.serviceApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-job-fallback-management.fullname" . }}-truefoundry-api
  labels:
    {{- include "spark-job-fallback-management.labels" . | nindent 4 }}
type: Opaque
stringData:
  service-api-token: {{ .Values.truefoundryApi.serviceApiToken | quote }}
{{- end }}
